server:
  port: 8021

spring:
#  配置数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.234.165:3306/jsekill?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: root
#    配置MQ
  #配置rabbitMq 服务器所在的主机和端口，以及用户名和密码
  rabbitmq:
    host: 192.168.234.167
    port: 5672
    username: seckill
    password: seckill
    #虚拟host
    virtual-host: /seckill
      #确认消息已发送到交换机(Exchange)
    publisher-confirm-type: correlated
      #确认消息已发送到队列(Queue)
    publisher-returns: true
  redis:
    # Redis服务器地址
    host: 192.168.234.169
    # Redis服务器端口号
    port: 6379
    # 使用的数据库索引，默认是0
    database: 0
    # 连接超时时间
    timeout: 2000000
    # 设置密码
#    password: "123456"
    lettuce:
      pool:
        # 最大阻塞等待时间，负数表示没有限制
        max-wait: 300
        # 连接池中的最大空闲连接
        max-idle: 5
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中最大连接数，负数表示没有限制
        max-active: 20
# 配置生成具体的mq或者名称
rabbitmqbean:
#  秒杀队列的名称
  seckillQueueName: 'seckill_queue'
#  秒杀队列绑定的主题交换机名称
  seckillTopicExchangeName: 'seckill_exchange'
#  秒杀队列的绑定键，这里没有使用匹配规则，而是直接映射
  seckillQueueKey: 'seckill'


#mybatis的配置
mybatis:
  mapper-locations: classpath:/Mapper/*.xml
#  软件包的别名
  type-aliases-package: com/su/jsekill_project/pojo
#  session的配置
mysession:
  sessionClassPath: org.apache.catalina.session.StandardSession

